export const environment = {
  mexicoBounds: [
    [14, -120], // Esquina suroeste de México
    [33, -86], // Esquina noreste de México
  ],
  urlMapoteca: 'https://cartografia.ife.org.mx/mapoteca/',
  urlDescargaBases:'https://storage.googleapis.com/mapoteca_next/',
  WMSURL: 'https://cartografia.ife.org.mx/global/wms/?SERVICE=WMS',
  WMSResource: 'wnacional',
  WMSPort: '5432',
  WMSCache: 'sige9',
  memoriaDistritacion1996: '53.53',
  memoriaDistritacion2005: '43.13',
  memoriaDistritacion2017: '16.04',
  acuerdosDistritacion17: 'https://cartografia.ife.org.mx/descargas/distritacion2017/acuerdos/',
  UrlINE: 'https://ine.mx/',
  urlTransmisionesEnVivo: 'https://ine.mx/transmisiones-en-vivo/',
  urlFacebook: 'https://www.facebook.com/INEMexico',
  urlX: 'https://twitter.com/INEMexico',
  urlYouTube: 'https://www.youtube.com/user/IFETV',
  urlInstagram: 'https://www.instagram.com/inemexico/?hl=es',
  urlTikTok: 'https://www.tiktok.com/@inemexico?lang=es',
  urlUbicaTuCassilla: 'https://ubicatucasilla.ine.mx/',
  urlUbicaTuModulo: 'https://ubicatumodulo.ine.mx/',
  urlEncuestaGoogle: 'https://docs.google.com/forms/d/e/1FAIpQLSf7UV34SYL1IjAbtld-ojV9213M_mjyBnaqBSZzTJzOOMv8tA/viewform?embedded=true',
  urlCentralElectoral: 'https://centralelectoral.ine.mx/search/cartograf%C3%ADa/',
  urlCECartografia: 'https://centralelectoral.ine.mx/2019/05/21/cartografia-electoral/',
  urlCETrabajoPermanente: 'https://centralelectoral.ine.mx/2022/12/16/el-ine-realiza-un-trabajo-permanente-en-cartografia-en-cada-uno-de-los-300-distritos-electorales/',
  urlCEModificacionCartografia: 'https://centralelectoral.ine.mx/2023/08/25/aprueba-ine-cambios-en-la-cartografia-electoral-del-pais-rumbo-al-proceso-electoral-del-2024/',
  urlCEOrganizaciónElectoral: 'https://centralelectoral.ine.mx/2017/08/03/sabias-que-para-una-mejor-organizacion-electoral-el-ine-realiza-una-subdivision-geografica-en-el-pais-llamada-cartografia-electoral/',
  urlINEGIEstadisticas: 'https://gaia.inegi.org.mx/mdm6/?v=bGF0OjIzLjMyMDA4LGxvbjotMTAyLjE0NTY1LHo6MixsOmNnZW9lbGVjdG9yYWxlcw==',
  urlPlataFormaDeTransparencia: 'https://www.plataformadetransparencia.org.mx/',
  ServerMapoteca: 'https://cartografia.ife.org.mx/',
  cartoBaseMapA: 'https://a.basemaps.cartocdn.com',
  cartoBaseMapB: 'https://b.basemaps.cartocdn.com',
  cartoBaseMapC: 'https://c.basemaps.cartocdn.com',
  fontsGStatic: 'https://fonts.gstatic.com',
  docsGoogle: 'https://docs.google.com/',
  guiaSIGE: 'https://storage.googleapis.com/sige_docs/guia_sige8.pdf',
  googleAnalyticsURL: 'https://www.google-analytics.com',
  googleTagManagerURL: 'https://www.googletagmanager.com ',
  googleAnalyticsID: 'G-JE1XQQSECY',
  scriptGoogleAnalyticsID: 'https://www.googletagmanager.com/gtag/js?id=G-JE1XQQSECY',

};
